---
- name: Configurar nginx

  hosts: default
  become: true

  tasks:
    - name: verificar si el repositorio esta disponible
      yum:
        name: [amazon-linux-extras]
        state: present

    - name: habilitar el repositorio de nginx
      shell: amazon-linux-extras enable nginx1

    - name: limpiar metadata
      command: yum clean metadata
      args:
        warn: no

    - name: install nginx
      yum:
        name: [nginx]
        state: latest

    - name: enable nginx service
      service:
        name: nginx
        enabled: true